const axios = require('axios');

const BASE_URL = 'https://edusmart-server.vercel.app';

// Sample university data with diverse information
const universities = [
  {
    name: "Harvard University",
    description: "Harvard University is a private Ivy League research university in Cambridge, Massachusetts. Established in 1636, Harvard is the oldest institution of higher education in the United States.",
    country: "USA",
    city: "Cambridge",
    state: "Massachusetts",
    website: "https://www.harvard.edu",
    contact_email: "admissions@harvard.edu",
    contact_phone: "+1-617-495-1000",
    established_year: 1636,
    type: "Private",
    ranking: 1,
    tuition_fee: 54269,
    application_fee: 75,
    acceptance_rate: 3.4,
    student_population: 23000,
    faculty_count: 2400,
    programs_offered: ["Medicine", "Law", "Business", "Engineering", "Liberal Arts"],
    facilities: ["Library", "Research Labs", "Sports Complex", "Medical Center"],
    image: "https://images.unsplash.com/photo-1562774053-701939374585?w=800&h=600&fit=crop",
    logo: "https://logos-world.net/wp-content/uploads/2021/09/Harvard-Logo.png",
    campus_size: "209 acres",
    campus_type: "Urban",
    accreditation: "NECHE",
    notable_alumni: ["Barack Obama", "Mark Zuckerberg", "Bill Gates"],
    region: "North America",
    ranking_type: "QS",
    ranking_year: 2024
  },
  {
    name: "Stanford University",
    description: "Stanford University is a private research university in Stanford, California. Known for its academic strength, wealth, and proximity to Silicon Valley.",
    country: "USA",
    city: "Stanford",
    state: "California",
    website: "https://www.stanford.edu",
    contact_email: "admission@stanford.edu",
    contact_phone: "+1-650-723-2300",
    established_year: 1885,
    type: "Private",
    ranking: 3,
    tuition_fee: 56169,
    application_fee: 90,
    acceptance_rate: 4.3,
    student_population: 17000,
    faculty_count: 2180,
    programs_offered: ["Computer Science", "Engineering", "Business", "Medicine", "AI"],
    facilities: ["Innovation Labs", "Library", "Sports Center", "Research Facilities"],
    image: "https://images.unsplash.com/photo-1498243691581-b145c3f54a5a?w=800&h=600&fit=crop",
    logo: "https://identity.stanford.edu/wp-content/uploads/sites/3/2020/07/stanford-logo.png",
    campus_size: "8180 acres",
    campus_type: "Suburban",
    accreditation: "WASC",
    notable_alumni: ["Elon Musk", "Larry Page", "Sergey Brin"],
    region: "North America",
    ranking_type: "QS",
    ranking_year: 2024
  },
  {
    name: "Massachusetts Institute of Technology",
    description: "MIT is a private research university in Cambridge, Massachusetts. Known for its innovation in science, technology, and engineering.",
    country: "USA",
    city: "Cambridge",
    state: "Massachusetts",
    website: "https://www.mit.edu",
    contact_email: "admissions@mit.edu",
    contact_phone: "+1-617-253-1000",
    established_year: 1861,
    type: "Private",
    ranking: 2,
    tuition_fee: 53790,
    application_fee: 75,
    acceptance_rate: 6.7,
    student_population: 11520,
    faculty_count: 1000,
    programs_offered: ["Engineering", "Computer Science", "Physics", "Mathematics", "AI"],
    facilities: ["Research Labs", "Innovation Center", "Library", "Tech Facilities"],
    image: "https://images.unsplash.com/photo-1564981797816-1043664bf78d?w=800&h=600&fit=crop",
    logo: "https://web.mit.edu/graphicidentity/logo/logofiles/mit-logo-red-gray-72x38.svg",
    campus_size: "168 acres",
    campus_type: "Urban",
    accreditation: "NECHE",
    notable_alumni: ["Tim Berners-Lee", "Buzz Aldrin", "Kofi Annan"],
    region: "North America",
    ranking_type: "QS",
    ranking_year: 2024
  },
  {
    name: "University of Oxford",
    description: "The University of Oxford is a collegiate research university in Oxford, England. It is the oldest university in the English-speaking world.",
    country: "United Kingdom",
    city: "Oxford",
    state: "England",
    website: "https://www.ox.ac.uk",
    contact_email: "admissions@ox.ac.uk",
    contact_phone: "+44-1865-270000",
    established_year: 1096,
    type: "Public",
    ranking: 4,
    tuition_fee: 35000,
    application_fee: 50,
    acceptance_rate: 17.5,
    student_population: 24000,
    faculty_count: 7000,
    programs_offered: ["Medicine", "Law", "Philosophy", "History", "Literature"],
    facilities: ["Bodleian Library", "Research Centers", "Museums", "Sports Facilities"],
    image: "https://images.unsplash.com/photo-1520637836862-4d197d17c93a?w=800&h=600&fit=crop",
    logo: "https://www.ox.ac.uk/sites/files/oxford/styles/ow_large_feature/public/field/field_image_main/Oxford_logo.jpg",
    campus_size: "Historic City Center",
    campus_type: "Urban",
    accreditation: "QAA",
    notable_alumni: ["Stephen Hawking", "Tony Blair", "Oscar Wilde"],
    region: "Europe",
    ranking_type: "QS",
    ranking_year: 2024
  },
  {
    name: "University of Cambridge",
    description: "The University of Cambridge is a collegiate research university in Cambridge, United Kingdom. Founded in 1209, it is the second-oldest university in the English-speaking world.",
    country: "United Kingdom",
    city: "Cambridge",
    state: "England",
    website: "https://www.cam.ac.uk",
    contact_email: "admissions@cam.ac.uk",
    contact_phone: "+44-1223-337733",
    established_year: 1209,
    type: "Public",
    ranking: 5,
    tuition_fee: 33000,
    application_fee: 50,
    acceptance_rate: 21.0,
    student_population: 23000,
    faculty_count: 6000,
    programs_offered: ["Mathematics", "Natural Sciences", "Engineering", "Medicine", "Computer Science"],
    facilities: ["University Library", "Research Labs", "Museums", "Sports Complex"],
    image: "https://images.unsplash.com/photo-1559827260-dc66d52bef19?w=800&h=600&fit=crop",
    logo: "https://www.cam.ac.uk/sites/www.cam.ac.uk/files/inner-images/logo.jpg",
    campus_size: "Historic Colleges",
    campus_type: "Urban",
    accreditation: "QAA",
    notable_alumni: ["Isaac Newton", "Charles Darwin", "Stephen Hawking"],
    region: "Europe",
    ranking_type: "QS",
    ranking_year: 2024
  },
  {
    name: "California Institute of Technology",
    description: "Caltech is a private research university in Pasadena, California. Known for its strength in science and engineering.",
    country: "USA",
    city: "Pasadena",
    state: "California",
    website: "https://www.caltech.edu",
    contact_email: "admissions@caltech.edu",
    contact_phone: "+1-626-395-6811",
    established_year: 1891,
    type: "Private",
    ranking: 6,
    tuition_fee: 56364,
    application_fee: 75,
    acceptance_rate: 6.4,
    student_population: 2240,
    faculty_count: 300,
    programs_offered: ["Physics", "Engineering", "Chemistry", "Biology", "Mathematics"],
    facilities: ["Jet Propulsion Laboratory", "Research Centers", "Observatory"],
    image: "https://images.unsplash.com/photo-1541339907198-e08756dedf3f?w=800&h=600&fit=crop",
    logo: "https://www.caltech.edu/sites/default/files/styles/article_image/public/2019-07/caltech_logo_0.jpg",
    campus_size: "124 acres",
    campus_type: "Suburban",
    accreditation: "WASC",
    notable_alumni: ["Kip Thorne", "Gordon Moore", "Frank Capra"],
    region: "North America",
    ranking_type: "QS",
    ranking_year: 2024
  },
  {
    name: "University of Toronto",
    description: "The University of Toronto is a public research university in Toronto, Ontario, Canada. It is one of the top universities in Canada.",
    country: "Canada",
    city: "Toronto",
    state: "Ontario",
    website: "https://www.utoronto.ca",
    contact_email: "admissions@utoronto.ca",
    contact_phone: "+1-416-978-2011",
    established_year: 1827,
    type: "Public",
    ranking: 25,
    tuition_fee: 25000,
    application_fee: 125,
    acceptance_rate: 43.0,
    student_population: 97000,
    faculty_count: 25000,
    programs_offered: ["Medicine", "Engineering", "Business", "Computer Science", "Arts"],
    facilities: ["Research Libraries", "Medical Facilities", "Innovation Labs"],
    image: "https://images.unsplash.com/photo-1523050854058-8df90110c9f1?w=800&h=600&fit=crop",
    logo: "https://www.utoronto.ca/sites/default/files/UofT-Logo-Blue_0.png",
    campus_size: "71 hectares",
    campus_type: "Urban",
    accreditation: "AUCC",
    notable_alumni: ["Lester B. Pearson", "Margaret Atwood", "David Cronenberg"],
    region: "North America",
    ranking_type: "QS",
    ranking_year: 2024
  },
  {
    name: "University of Melbourne",
    description: "The University of Melbourne is a public research university located in Melbourne, Australia. It is consistently ranked among the leading universities in the world.",
    country: "Australia",
    city: "Melbourne",
    state: "Victoria",
    website: "https://www.unimelb.edu.au",
    contact_email: "admissions@unimelb.edu.au",
    contact_phone: "+61-3-9035-5511",
    established_year: 1853,
    type: "Public",
    ranking: 14,
    tuition_fee: 35000,
    application_fee: 100,
    acceptance_rate: 70.0,
    student_population: 50000,
    faculty_count: 8000,
    programs_offered: ["Medicine", "Law", "Engineering", "Business", "Arts"],
    facilities: ["Research Centers", "Medical School", "Innovation Precinct"],
    image: "https://images.unsplash.com/photo-1523050854058-8df90110c9f1?w=800&h=600&fit=crop",
    logo: "https://www.unimelb.edu.au/__data/assets/image/0004/2271022/university-of-melbourne-logo.png",
    campus_size: "Multiple campuses",
    campus_type: "Urban",
    accreditation: "TEQSA",
    notable_alumni: ["Julia Gillard", "Peter Singer", "Germaine Greer"],
    region: "Oceania",
    ranking_type: "QS",
    ranking_year: 2024
  },
  {
    name: "National University of Singapore",
    description: "The National University of Singapore is a national public research university in Singapore. It is the oldest autonomous university in the country.",
    country: "Singapore",
    city: "Singapore",
    state: "Singapore",
    website: "https://www.nus.edu.sg",
    contact_email: "admissions@nus.edu.sg",
    contact_phone: "+65-6516-6666",
    established_year: 1905,
    type: "Public",
    ranking: 8,
    tuition_fee: 30000,
    application_fee: 50,
    acceptance_rate: 5.0,
    student_population: 40000,
    faculty_count: 2500,
    programs_offered: ["Engineering", "Computer Science", "Business", "Medicine", "Law"],
    facilities: ["Research Institutes", "Innovation Centers", "Medical Facilities"],
    image: "https://images.unsplash.com/photo-1562774053-701939374585?w=800&h=600&fit=crop",
    logo: "https://www.nus.edu.sg/images/default-source/base/logo.png",
    campus_size: "150 hectares",
    campus_type: "Urban",
    accreditation: "EQA",
    notable_alumni: ["Lee Hsien Loong", "Goh Chok Tong", "Tony Tan"],
    region: "Asia",
    ranking_type: "QS",
    ranking_year: 2024
  },
  {
    name: "University of Tokyo",
    description: "The University of Tokyo is a public research university in Tokyo, Japan. It is the first university established in Japan and one of the most prestigious.",
    country: "Japan",
    city: "Tokyo",
    state: "Tokyo",
    website: "https://www.u-tokyo.ac.jp",
    contact_email: "admissions@u-tokyo.ac.jp",
    contact_phone: "+81-3-3812-2111",
    established_year: 1877,
    type: "Public",
    ranking: 23,
    tuition_fee: 15000,
    application_fee: 30,
    acceptance_rate: 35.0,
    student_population: 28000,
    faculty_count: 4000,
    programs_offered: ["Engineering", "Medicine", "Science", "Law", "Economics"],
    facilities: ["Research Centers", "Libraries", "Medical Hospital"],
    image: "https://images.unsplash.com/photo-1480796927426-f609979314bd?w=800&h=600&fit=crop",
    logo: "https://www.u-tokyo.ac.jp/content/400002279.png",
    campus_size: "Multiple campuses",
    campus_type: "Urban",
    accreditation: "NIAD-QE",
    notable_alumni: ["Yukio Hatoyama", "Kenzaburo Oe", "Hideki Yukawa"],
    region: "Asia",
    ranking_type: "QS",
    ranking_year: 2024
  }
];

// Add more universities to reach 50
const additionalUniversities = [
  {
    name: "ETH Zurich",
    description: "ETH Zurich is a public research university in Zurich, Switzerland. Known for science, technology, engineering and mathematics.",
    country: "Switzerland",
    city: "Zurich",
    state: "Zurich",
    website: "https://ethz.ch",
    contact_email: "admissions@ethz.ch",
    contact_phone: "+41-44-632-1111",
    established_year: 1855,
    type: "Public",
    ranking: 7,
    tuition_fee: 1500,
    application_fee: 150,
    acceptance_rate: 8.0,
    student_population: 22200,
    faculty_count: 500,
    programs_offered: ["Engineering", "Computer Science", "Physics", "Mathematics", "Chemistry"],
    facilities: ["Research Labs", "Innovation Park", "Library"],
    image: "https://images.unsplash.com/photo-1541339907198-e08756dedf3f?w=800&h=600&fit=crop",
    logo: "https://ethz.ch/etc/designs/ethz/img/header/ethz_logo_black.svg",
    campus_size: "Multiple locations",
    campus_type: "Urban",
    accreditation: "AAQ",
    notable_alumni: ["Albert Einstein", "Wilhelm Röntgen", "Richard Ernst"],
    region: "Europe",
    ranking_type: "QS",
    ranking_year: 2024
  },
  {
    name: "University College London",
    description: "UCL is a public research university in London, England. It was the first university institution to be established in London.",
    country: "United Kingdom",
    city: "London",
    state: "England",
    website: "https://www.ucl.ac.uk",
    contact_email: "admissions@ucl.ac.uk",
    contact_phone: "+44-20-7679-2000",
    established_year: 1826,
    type: "Public",
    ranking: 9,
    tuition_fee: 28000,
    application_fee: 50,
    acceptance_rate: 63.0,
    student_population: 42000,
    faculty_count: 7000,
    programs_offered: ["Medicine", "Engineering", "Arts", "Sciences", "Law"],
    facilities: ["Research Centers", "Museums", "Hospitals", "Libraries"],
    image: "https://images.unsplash.com/photo-1520637736862-4d197d17c93a?w=800&h=600&fit=crop",
    logo: "https://www.ucl.ac.uk/visual-identity/logos-and-brand-assets/ucl-logo",
    campus_size: "Central London",
    campus_type: "Urban",
    accreditation: "QAA",
    notable_alumni: ["Alexander Graham Bell", "Mahatma Gandhi", "Christopher Nolan"],
    region: "Europe",
    ranking_type: "QS",
    ranking_year: 2024
  },
  {
    name: "Imperial College London",
    description: "Imperial College London is a public research university in London, England. Specializes in science, engineering, medicine and business.",
    country: "United Kingdom",
    city: "London",
    state: "England",
    website: "https://www.imperial.ac.uk",
    contact_email: "admissions@imperial.ac.uk",
    contact_phone: "+44-20-7589-5111",
    established_year: 1907,
    type: "Public",
    ranking: 6,
    tuition_fee: 32000,
    application_fee: 50,
    acceptance_rate: 14.3,
    student_population: 17000,
    faculty_count: 4000,
    programs_offered: ["Engineering", "Medicine", "Natural Sciences", "Business"],
    facilities: ["Research Labs", "Innovation Hub", "Medical School"],
    image: "https://images.unsplash.com/photo-1564981797816-1043664bf78d?w=800&h=600&fit=crop",
    logo: "https://www.imperial.ac.uk/ImageCropToolT4/imageTool/uploaded-images/Blue-on-white--tojpeg_1495792235526_x1.jpg",
    campus_size: "South Kensington",
    campus_type: "Urban",
    accreditation: "QAA",
    notable_alumni: ["H.G. Wells", "Alexander Fleming", "Brian May"],
    region: "Europe",
    ranking_type: "QS",
    ranking_year: 2024
  },
  {
    name: "University of Chicago",
    description: "The University of Chicago is a private research university in Chicago, Illinois. Known for its influential contributions to many academic fields.",
    country: "USA",
    city: "Chicago",
    state: "Illinois",
    website: "https://www.uchicago.edu",
    contact_email: "admissions@uchicago.edu",
    contact_phone: "+1-773-702-1234",
    established_year: 1890,
    type: "Private",
    ranking: 10,
    tuition_fee: 59298,
    application_fee: 75,
    acceptance_rate: 7.4,
    student_population: 17000,
    faculty_count: 2200,
    programs_offered: ["Economics", "Physics", "Medicine", "Law", "Business"],
    facilities: ["Research Centers", "Libraries", "Medical Center"],
    image: "https://images.unsplash.com/photo-1498243691581-b145c3f54a5a?w=800&h=600&fit=crop",
    logo: "https://www.uchicago.edu/about/brand/img/logo-university.png",
    campus_size: "217 acres",
    campus_type: "Urban",
    accreditation: "HLC",
    notable_alumni: ["Barack Obama", "Milton Friedman", "Carl Sagan"],
    region: "North America",
    ranking_type: "QS",
    ranking_year: 2024
  },
  {
    name: "Yale University",
    description: "Yale University is a private Ivy League research university in New Haven, Connecticut. Known for its outstanding undergraduate program.",
    country: "USA",
    city: "New Haven",
    state: "Connecticut",
    website: "https://www.yale.edu",
    contact_email: "admissions@yale.edu",
    contact_phone: "+1-203-432-4771",
    established_year: 1701,
    type: "Private",
    ranking: 16,
    tuition_fee: 59950,
    application_fee: 80,
    acceptance_rate: 6.1,
    student_population: 13500,
    faculty_count: 4400,
    programs_offered: ["Liberal Arts", "Medicine", "Law", "Business", "Drama"],
    facilities: ["Libraries", "Art Galleries", "Medical School", "Research Centers"],
    image: "https://images.unsplash.com/photo-1562774053-701939374585?w=800&h=600&fit=crop",
    logo: "https://www.yale.edu/sites/default/files/yale-logo.svg",
    campus_size: "310 acres",
    campus_type: "Urban",
    accreditation: "NECHE",
    notable_alumni: ["George W. Bush", "Hillary Clinton", "Meryl Streep"],
    region: "North America",
    ranking_type: "QS",
    ranking_year: 2024
  },
  {
    name: "Princeton University",
    description: "Princeton University is a private Ivy League research university in Princeton, New Jersey. Known for its undergraduate focus and beautiful campus.",
    country: "USA",
    city: "Princeton",
    state: "New Jersey",
    website: "https://www.princeton.edu",
    contact_email: "admissions@princeton.edu",
    contact_phone: "+1-609-258-3000",
    established_year: 1746,
    type: "Private",
    ranking: 12,
    tuition_fee: 56010,
    application_fee: 70,
    acceptance_rate: 5.8,
    student_population: 5400,
    faculty_count: 1200,
    programs_offered: ["Liberal Arts", "Engineering", "Public Policy", "Economics"],
    facilities: ["Research Centers", "Art Museum", "Library System"],
    image: "https://images.unsplash.com/photo-1559827260-dc66d52bef19?w=800&h=600&fit=crop",
    logo: "https://www.princeton.edu/sites/default/files/styles/1x/public/images/2018/10/PU-standard.png",
    campus_size: "600 acres",
    campus_type: "Suburban",
    accreditation: "MSCHE",
    notable_alumni: ["Woodrow Wilson", "F. Scott Fitzgerald", "Jeff Bezos"],
    region: "North America",
    ranking_type: "QS",
    ranking_year: 2024
  },
  {
    name: "Columbia University",
    description: "Columbia University is a private Ivy League research university in New York City. Known for journalism, business, and medicine programs.",
    country: "USA",
    city: "New York",
    state: "New York",
    website: "https://www.columbia.edu",
    contact_email: "admissions@columbia.edu",
    contact_phone: "+1-212-854-1754",
    established_year: 1754,
    type: "Private",
    ranking: 19,
    tuition_fee: 61850,
    application_fee: 85,
    acceptance_rate: 5.1,
    student_population: 33000,
    faculty_count: 4000,
    programs_offered: ["Journalism", "Business", "Medicine", "Law", "Engineering"],
    facilities: ["Medical Center", "Libraries", "Research Labs", "Arts Centers"],
    image: "https://images.unsplash.com/photo-1541339907198-e08756dedf3f?w=800&h=600&fit=crop",
    logo: "https://www.columbia.edu/content/themes/custom/columbia/assets/img/logo.svg",
    campus_size: "36 acres",
    campus_type: "Urban",
    accreditation: "MSCHE",
    notable_alumni: ["Barack Obama", "Warren Buffett", "Langston Hughes"],
    region: "North America",
    ranking_type: "QS",
    ranking_year: 2024
  },
  {
    name: "University of Pennsylvania",
    description: "The University of Pennsylvania is a private Ivy League research university in Philadelphia. Known for its business school and medical programs.",
    country: "USA",
    city: "Philadelphia",
    state: "Pennsylvania",
    website: "https://www.upenn.edu",
    contact_email: "admissions@upenn.edu",
    contact_phone: "+1-215-898-5000",
    established_year: 1740,
    type: "Private",
    ranking: 13,
    tuition_fee: 60042,
    application_fee: 75,
    acceptance_rate: 8.4,
    student_population: 25000,
    faculty_count: 4700,
    programs_offered: ["Business", "Medicine", "Engineering", "Nursing", "Veterinary"],
    facilities: ["Medical Center", "Business School", "Research Centers"],
    image: "https://images.unsplash.com/photo-1523050854058-8df90110c9f1?w=800&h=600&fit=crop",
    logo: "https://www.upenn.edu/sites/default/files/UPenn_logo-blue.png",
    campus_size: "299 acres",
    campus_type: "Urban",
    accreditation: "MSCHE",
    notable_alumni: ["Donald Trump", "Warren Buffett", "Noam Chomsky"],
    region: "North America",
    ranking_type: "QS",
    ranking_year: 2024
  },
  {
    name: "University of Michigan",
    description: "The University of Michigan is a public research university in Ann Arbor, Michigan. Known for its comprehensive academic programs and research.",
    country: "USA",
    city: "Ann Arbor",
    state: "Michigan",
    website: "https://www.umich.edu",
    contact_email: "admissions@umich.edu",
    contact_phone: "+1-734-764-1817",
    established_year: 1817,
    type: "Public",
    ranking: 21,
    tuition_fee: 15262,
    application_fee: 75,
    acceptance_rate: 23.0,
    student_population: 47000,
    faculty_count: 6700,
    programs_offered: ["Engineering", "Business", "Medicine", "Law", "Public Policy"],
    facilities: ["Research Centers", "Medical Center", "Libraries", "Sports Facilities"],
    image: "https://images.unsplash.com/photo-1564981797816-1043664bf78d?w=800&h=600&fit=crop",
    logo: "https://www.umich.edu/skins/um2013/media/images/umich-logo.png",
    campus_size: "3207 acres",
    campus_type: "Urban",
    accreditation: "HLC",
    notable_alumni: ["Gerald Ford", "Larry Page", "Tom Brady"],
    region: "North America",
    ranking_type: "QS",
    ranking_year: 2024
  },
  {
    name: "University of California, Berkeley",
    description: "UC Berkeley is a public research university in Berkeley, California. Known for its academic excellence and social activism.",
    country: "USA",
    city: "Berkeley",
    state: "California",
    website: "https://www.berkeley.edu",
    contact_email: "admissions@berkeley.edu",
    contact_phone: "+1-510-642-6000",
    established_year: 1868,
    type: "Public",
    ranking: 27,
    tuition_fee: 14226,
    application_fee: 70,
    acceptance_rate: 16.3,
    student_population: 45000,
    faculty_count: 3000,
    programs_offered: ["Engineering", "Computer Science", "Business", "Law", "Public Policy"],
    facilities: ["Research Labs", "Libraries", "Innovation Centers"],
    image: "https://images.unsplash.com/photo-1498243691581-b145c3f54a5a?w=800&h=600&fit=crop",
    logo: "https://www.berkeley.edu/brand/img/seals/ucbseal_139_540.png",
    campus_size: "1232 acres",
    campus_type: "Urban",
    accreditation: "WASC",
    notable_alumni: ["Steve Wozniak", "Eric Schmidt", "Jennifer Granholm"],
    region: "North America",
    ranking_type: "QS",
    ranking_year: 2024
  }
];

// Combine all universities
const allUniversities = [...universities, ...additionalUniversities];

// Function to create a university
async function createUniversity(universityData) {
  try {
    const response = await axios.post(`${BASE_URL}/api/universities`, universityData, {
      headers: {
        'Content-Type': 'application/json',
        'Authorization': 'Bearer admin-token' // You'll need to replace this with actual admin token
      }
    });
    
    console.log(`✅ Created: ${universityData.name}`);
    return response.data;
  } catch (error) {
    console.error(`❌ Failed to create ${universityData.name}:`, error.response?.data || error.message);
    return null;
  }
}

// Function to add all universities
async function addAllUniversities() {
  console.log(`🚀 Starting to add ${allUniversities.length} universities...`);
  
  for (let i = 0; i < allUniversities.length; i++) {
    const university = allUniversities[i];
    console.log(`\n📚 Adding university ${i + 1}/${allUniversities.length}: ${university.name}`);
    
    await createUniversity(university);
    
    // Add a small delay to avoid overwhelming the server
    await new Promise(resolve => setTimeout(resolve, 1000));
  }
  
  console.log('\n🎉 Finished adding universities!');
}

// Run the script
addAllUniversities().catch(console.error); 