service: edusmart-api

frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs18.x
  stage: ${opt:stage, 'dev'}
  region: ${opt:region, 'us-east-1'}
  environment:
    SUPABASE_URL: ${env:SUPABASE_URL}
    SUPABASE_KEY: ${env:SUPABASE_KEY}
    JWT_SECRET: ${env:JWT_SECRET}

functions:
  api:
    handler: src/serverless.handler
    events:
      - httpApi: '*'
    
plugins:
  - serverless-offline

custom:
  serverless-offline:
    httpPort: 8000 