name = "edusmart-api"
main = "src/worker.js"
compatibility_date = "2024-09-23"
compatibility_flags = ["nodejs_compat"]
node_compat = true

[env.production]
name = "edusmart-api-production"

[env.staging]
name = "edusmart-api-staging"

# Environment variables (you'll need to set these via wrangler secret put)
# DATABASE_URL, JWT_SECRET, etc.

# If you need to store files, you can use R2 bucket
# [[r2_buckets]]
# binding = "MY_BUCKET"
# bucket_name = "edusmart-uploads"

# For database connections, you might need D1 or external connections
# [[d1_databases]]
# binding = "DB"
# database_name = "edusmart-db"
# database_id = "your-database-id" 