name = "edusmart-api"
compatibility_date = "2024-09-23"
compatibility_flags = ["nodejs_compat"]
node_compat = true

# Pages-specific configuration
pages_build_output_dir = "/"

[build]
command = "npm install"

[build.environment_variables]
NODE_ENV = "production" 